/* Generated by build-judge-samples.py. Real captured runs. */
window.JUDGE_SAMPLES = {
  "captured_at": "2026-10-05",
  "model": "claude-haiku-4-5-20251001",
  "temperature": 1.0,
  "runs_per_case": 8,
  "source": "HaluEval (QA split), MIT; knowledge/question/reference from HotpotQA, CC BY-SA 4.0",
  "cases": [
    {
      "id": "easy",
      "label": "Clear-cut case",
      "blurb": "The answer contradicts the context outright.",
      "knowledge": "750 Seventh Avenue is a 615 ft (187m) tall Class-A office skyscraper in New York City.101 Park Avenue is a 629 ft tall skyscraper in New York City, New York.",
      "question": "750 7th Avenue and 101 Park Avenue, are located in which city?",
      "reference": "New York City",
      "answer": "750 7th Avenue and 101 Park Avenue are located in Albany, New York.",
      "dataset_label": "hallucinated",
      "note": "The context says New York City twice. The answer says Albany.",
      "runs": [
        {
          "accuracy": {
            "verdict": "fail",
            "why": "The context explicitly states both buildings are in New York City, not Albany, New York."
          },
          "groundedness": {
            "verdict": "fail",
            "why": "The answer directly contradicts the context which clearly identifies both locations as New York City."
          },
          "completeness": {
            "verdict": "pass",
            "why": "The answer does provide a location answer for both buildings as requested."
          },
          "actionability": {
            "verdict": "fail",
            "why": "While the answer is clear in form, it provides incorrect information that would mislead the user."
          },
          "overall": {
            "verdict": "fail",
            "why": "The answer is factually incorrect and unsupported by the context, stating Albany instead of New York City."
          }
        },
        {
          "accuracy": {
            "verdict": "fail",
            "why": "The context explicitly states both buildings are in New York City, not Albany, New York."
          },
          "groundedness": {
            "verdict": "fail",
            "why": "The answer contradicts the context which clearly identifies both buildings as being in New York City."
          },
          "completeness": {
            "verdict": "pass",
            "why": "The answer directly addresses which city both buildings are located in."
          },
          "actionability": {
            "verdict": "pass",
            "why": "The answer is clear and provides a direct response to the question asked."
          },
          "overall": {
            "verdict": "fail",
            "why": "The answer is factually incorrect and contradicts the provided context, making it unreliable despite being otherwise well-structured."
          }
        },
        {
          "accuracy": {
            "verdict": "fail",
            "why": "The context explicitly states both buildings are in New York City, not Albany, New York."
          },
          "groundedness": {
            "verdict": "fail",
            "why": "The answer contradicts the context which clearly identifies both buildings as being in New York City."
          },
          "completeness": {
            "verdict": "pass",
            "why": "The answer directly addresses which city both buildings are located in."
          },
          "actionability": {
            "verdict": "fail",
            "why": "While the format is clear, the answer provides false information that would mislead the user."
          },
          "overall": {
            "verdict": "fail",
            "why": "The answer is factually incorrect and contradicts the provided context by stating Albany instead of New York City."
          }
        },
        {
          "accuracy": {
            "verdict": "fail",
            "why": "The context explicitly states both buildings are in New York City, not Albany, New York."
          },
          "groundedness": {
            "verdict": "fail",
            "why": "The answer contradicts the context, which clearly identifies both buildings as being in New York City."
          },
          "completeness": {
            "verdict": "pass",
            "why": "The answer does directly address which city both buildings are located in."
          },
          "actionability": {
            "verdict": "pass",
            "why": "The answer is clear and provides a direct response to the question asked."
          },
          "overall": {
            "verdict": "fail",
            "why": "The answer is factually incorrect and unsupported by the provided context, which is the most critical failure."
          }
        },
        {
          "accuracy": {
            "verdict": "fail",
            "why": "The context explicitly states both buildings are located in New York City, not Albany, New York."
          },
          "groundedness": {
            "verdict": "fail",
            "why": "The answer contradicts the context, which clearly identifies both buildings as being in New York City."
          },
          "completeness": {
            "verdict": "fail",
            "why": "While the answer attempts to identify a city, it provides the wrong city, failing to correctly answer the question."
          },
          "actionability": {
            "verdict": "fail",
            "why": "The answer is clear in format but provides incorrect information that would mislead the user."
          },
          "overall": {
            "verdict": "fail",
            "why": "The answer is factually incorrect, contradicts the provided context, and gives the wrong city (Albany instead of New York City)."
          }
        },
        {
          "accuracy": {
            "verdict": "fail",
            "why": "The context explicitly states both buildings are in New York City, not Albany, New York."
          },
          "groundedness": {
            "verdict": "fail",
            "why": "The answer contradicts the context which clearly identifies both buildings as being located in New York City."
          },
          "completeness": {
            "verdict": "pass",
            "why": "The answer does directly address which city both buildings are located in."
          },
          "actionability": {
            "verdict": "pass",
            "why": "The answer is clear and provides a specific city name as requested."
          },
          "overall": {
            "verdict": "fail",
            "why": "The answer is factually incorrect and contradicts the provided context, making it an unacceptable response despite being complete and actionable."
          }
        },
        {
          "accuracy": {
            "verdict": "fail",
            "why": "The context explicitly states both buildings are in New York City, not Albany, New York."
          },
          "groundedness": {
            "verdict": "fail",
            "why": "The answer contradicts the context which clearly identifies both buildings as being in New York City."
          },
          "completeness": {
            "verdict": "pass",
            "why": "The answer directly addresses which city the buildings are located in."
          },
          "actionability": {
            "verdict": "pass",
            "why": "The answer provides a clear, direct statement about the location of both buildings."
          },
          "overall": {
            "verdict": "fail",
            "why": "The answer is factually incorrect and not supported by the provided context, despite being complete and actionable."
          }
        },
        {
          "accuracy": {
            "verdict": "fail",
            "why": "The context explicitly states both buildings are located in New York City, not Albany, New York."
          },
          "groundedness": {
            "verdict": "fail",
            "why": "The answer contradicts the context which clearly identifies both buildings as being in New York City."
          },
          "completeness": {
            "verdict": "pass",
            "why": "The answer does address which city the buildings are located in, even though it provides incorrect information."
          },
          "actionability": {
            "verdict": "pass",
            "why": "The answer is clear and directly states a location, making it actionable as a response."
          },
          "overall": {
            "verdict": "fail",
            "why": "The answer provides factually incorrect information that directly contradicts the provided context."
          }
        }
      ]
    },
    {
      "id": "hard",
      "label": "Boundary case",
      "blurb": "The dataset labels this a hallucination. Reasonable people disagree.",
      "knowledge": "Donahue replaced Kelli Ward who resigned to run for the United States Senate.Kelli Ward (\"nee\" Kaznoski; born January 25, 1969) is an American politician and osteopathic physician.",
      "question": "Which American politician did Donahue replace?",
      "reference": "Kelli Ward",
      "answer": "Donahue replaced Kelli Ward's position.",
      "dataset_label": "hallucinated",
      "note": "It names the right person but answers obliquely. Whether that is a hallucination or just awkward phrasing is a judgement call, which is exactly why it is here.",
      "runs": [
        {
          "accuracy": {
            "verdict": "pass",
            "why": "The answer is factually correct - Donahue did replace Kelli Ward."
          },
          "groundedness": {
            "verdict": "pass",
            "why": "The claim is directly supported by the context which states 'Donahue replaced Kelli Ward.'"
          },
          "completeness": {
            "verdict": "fail",
            "why": "The answer says 'position' instead of identifying Kelli Ward as the American politician, which is what the question asked for."
          },
          "actionability": {
            "verdict": "pass",
            "why": "The answer clearly communicates that Kelli Ward is the person Donahue replaced."
          },
          "overall": {
            "verdict": "pass",
            "why": "While the phrasing is slightly awkward by using 'position' rather than directly naming Kelli Ward as the politician, the answer is accurate, grounded, and usable."
          }
        },
        {
          "accuracy": {
            "verdict": "pass",
            "why": "The answer correctly identifies that Donahue replaced Kelli Ward, which is supported by the context."
          },
          "groundedness": {
            "verdict": "pass",
            "why": "The claim that Donahue replaced Kelli Ward's position is directly stated in the context."
          },
          "completeness": {
            "verdict": "fail",
            "why": "The answer identifies Kelli Ward but does not name her or provide identifying details about who she is as an American politician."
          },
          "actionability": {
            "verdict": "pass",
            "why": "The answer clearly states that Donahue replaced Kelli Ward's position, directly answering the question asked."
          },
          "overall": {
            "verdict": "pass",
            "why": "While the answer could be more complete by naming Kelli Ward explicitly, it accurately and directly answers the question with information grounded in the context."
          }
        },
        {
          "accuracy": {
            "verdict": "pass",
            "why": "The statement is factually correct - Donahue did replace Kelli Ward according to the context."
          },
          "groundedness": {
            "verdict": "pass",
            "why": "The claim is directly supported by the opening sentence of the context."
          },
          "completeness": {
            "verdict": "fail",
            "why": "The answer avoids naming Kelli Ward directly when the question explicitly asks which politician Donahue replaced."
          },
          "actionability": {
            "verdict": "fail",
            "why": "The phrasing 'replaced Kelli Ward's position' is awkward and indirect when 'Donahue replaced Kelli Ward' would be clearer."
          },
          "overall": {
            "verdict": "fail",
            "why": "While technically accurate and grounded, the answer circumlocutes the direct answer ('Kelli Ward') that the question asks for, making it unnecessarily unclear."
          }
        },
        {
          "accuracy": {
            "verdict": "pass",
            "why": "The answer correctly states that Donahue replaced Kelli Ward, which is factually accurate according to the context."
          },
          "groundedness": {
            "verdict": "pass",
            "why": "The claim is directly supported by the first sentence of the context: 'Donahue replaced Kelli Ward who resigned to run for the United States Senate.'"
          },
          "completeness": {
            "verdict": "pass",
            "why": "The answer identifies Kelli Ward as the American politician Donahue replaced, directly answering the question asked."
          },
          "actionability": {
            "verdict": "fail",
            "why": "The phrasing 'replaced Kelli Ward's position' is slightly awkward; it would be clearer to simply say 'Donahue replaced Kelli Ward' or 'Donahue replaced the position held by Kelli Ward.'"
          },
          "overall": {
            "verdict": "pass",
            "why": "The answer is accurate, grounded in context, and complete, though the phrasing could be slightly improved for clarity."
          }
        },
        {
          "accuracy": {
            "verdict": "pass",
            "why": "The answer correctly states that Donahue replaced Kelli Ward's position, which aligns with the context."
          },
          "groundedness": {
            "verdict": "pass",
            "why": "The claim is directly supported by the context which states 'Donahue replaced Kelli Ward who resigned to run for the United States Senate.'"
          },
          "completeness": {
            "verdict": "fail",
            "why": "The answer fails to identify Kelli Ward by name as the politician Donahue replaced, instead using the vague phrase 'position' when the question specifically asks which politician was replaced."
          },
          "actionability": {
            "verdict": "fail",
            "why": "The answer is unclear and doesn't directly name the politician, making it less useful as a straightforward response to the question asked."
          },
          "overall": {
            "verdict": "fail",
            "why": "While factually accurate and grounded, the answer is incomplete and poorly actionable because it avoids directly naming Kelli Ward as the politician replaced, which is what the question explicitly asks for."
          }
        },
        {
          "accuracy": {
            "verdict": "pass",
            "why": "The answer correctly states that Donahue replaced Kelli Ward's position, which is supported by the context."
          },
          "groundedness": {
            "verdict": "pass",
            "why": "The claim is directly supported by the opening sentence of the context: 'Donahue replaced Kelli Ward who resigned to run for the United States Senate.'"
          },
          "completeness": {
            "verdict": "fail",
            "why": "The answer should have named Kelli Ward as the politician Donahue replaced, but instead uses the indirect phrase 'Kelli Ward's position' rather than directly identifying her."
          },
          "actionability": {
            "verdict": "fail",
            "why": "The answer is awkwardly phrased with 'Kelli Ward's position' rather than directly stating 'Donahue replaced Kelli Ward' or 'Kelli Ward is the American politician Donahue replaced.'"
          },
          "overall": {
            "verdict": "fail",
            "why": "While technically accurate and grounded, the answer is awkwardly constructed and fails to directly answer the straightforward question about which politician was replaced."
          }
        },
        {
          "accuracy": {
            "verdict": "pass",
            "why": "The answer correctly states that Donahue replaced Kelli Ward's position, which is factually accurate according to the context."
          },
          "groundedness": {
            "verdict": "pass",
            "why": "The claim is directly supported by the context statement 'Donahue replaced Kelli Ward who resigned to run for the United States Senate.'"
          },
          "completeness": {
            "verdict": "fail",
            "why": "The answer fails to identify Kelli Ward by name as the American politician replaced, instead using the indirect phrasing 'Kelli Ward's position.'"
          },
          "actionability": {
            "verdict": "fail",
            "why": "The answer is awkwardly phrased with 'position' when the question specifically asks which American politician was replaced, requiring a clearer identification of the person."
          },
          "overall": {
            "verdict": "fail",
            "why": "While factually accurate and grounded, the answer is incomplete and poorly phrased, failing to directly identify Kelli Ward as the politician in response to the specific question asked."
          }
        },
        {
          "accuracy": {
            "verdict": "pass",
            "why": "The answer correctly states that Donahue replaced Kelli Ward's position, which is supported by the context."
          },
          "groundedness": {
            "verdict": "pass",
            "why": "The claim is directly supported by the first sentence of the context stating 'Donahue replaced Kelli Ward.'"
          },
          "completeness": {
            "verdict": "fail",
            "why": "The question asks which American politician Donahue replaced, and while the answer identifies the person (Kelli Ward), it awkwardly phrases it as 'position' rather than directly naming the politician."
          },
          "actionability": {
            "verdict": "fail",
            "why": "The phrasing 'replaced Kelli Ward's position' is awkward and indirectly answers the straightforward question about which politician was replaced."
          },
          "overall": {
            "verdict": "fail",
            "why": "While factually accurate and grounded, the answer fails to directly and clearly state that Donahue replaced Kelli Ward, instead using awkward phrasing that diminishes clarity and actionability."
          }
        }
      ]
    }
  ]
};
